
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."clan" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone,
    "name" "text",
    "nicknames" "text",
    "summary" "text",
    "description" "text",
    "logo" "text",
    "symbol" "text",
    "artwork" "text",
    "bane" "text",
    "compulsion" "text",
    "quote" "json",
    "content_source_id" bigint NOT NULL,
    "characteristics" "json"[]
);

ALTER TABLE "public"."clan" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."clan_disciplines" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone,
    "clan_id" bigint,
    "discipline_id" bigint,
    "note" "text"
);

ALTER TABLE "public"."clan_disciplines" OWNER TO "postgres";

ALTER TABLE "public"."clan_disciplines" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clan_disciplines_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."content_source" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone,
    "name" "text",
    "url" "text",
    "description" "text",
    "splat" "text",
    "edition" "text"
);

ALTER TABLE "public"."content_source" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."discipline" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "type" "text",
    "masquerade_threat" "text",
    "resonance" "text",
    "quote" "jsonb",
    "description" "text",
    "rombo" character varying,
    "artwork" character varying,
    "characteristics" "json"[],
    "prerequisite_id" bigint
);

ALTER TABLE "public"."discipline" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."loresheet" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "description" "text",
    "artwork" character varying,
    "sect_id" bigint,
    "clan_id" bigint,
    "name" character varying,
    "content_source_id" bigint DEFAULT '1'::bigint
);

ALTER TABLE "public"."loresheet" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."loresheet_benefit" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "loresheet_id" bigint NOT NULL,
    "name" character varying,
    "level" smallint DEFAULT '1'::smallint,
    "description" "text"
);

ALTER TABLE "public"."loresheet_benefit" OWNER TO "postgres";

ALTER TABLE "public"."loresheet_benefit" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."loresheet_benefit_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."loresheet" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."loresheet_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."power" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "discipline_id" bigint NOT NULL,
    "level" bigint NOT NULL,
    "content_source_id" bigint DEFAULT '1'::bigint,
    "description" "text",
    "cost" character varying,
    "summary" "text",
    "duration" character varying,
    "challenge_pool" "json",
    "amalgam" "json",
    "prerequisite_id" bigint,
    "process" "text",
    "ingredients" "json"[]
);

ALTER TABLE "public"."power" OWNER TO "postgres";

ALTER TABLE "public"."power" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."power_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."predator_type" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "description" "text"
);

ALTER TABLE "public"."predator_type" OWNER TO "postgres";

ALTER TABLE "public"."predator_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."predator_type_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."sect" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying,
    "nicknames" character varying,
    "description" "text",
    "artwork" character varying,
    "logo" character varying,
    "symbol" character varying,
    "content_source_id" bigint,
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL
);

ALTER TABLE "public"."sect" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."sect_clans" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone,
    "sect_id" bigint,
    "clan_id" bigint,
    "note" "text"
);

ALTER TABLE "public"."sect_clans" OWNER TO "postgres";

ALTER TABLE "public"."sect" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sect_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."clan_disciplines"
    ADD CONSTRAINT "clan_disciplines_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."clan"
    ADD CONSTRAINT "clan_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."content_source"
    ADD CONSTRAINT "content_source_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."discipline"
    ADD CONSTRAINT "disipline_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."loresheet_benefit"
    ADD CONSTRAINT "loresheet_benefit_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."loresheet"
    ADD CONSTRAINT "loresheet_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."power"
    ADD CONSTRAINT "power_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."predator_type"
    ADD CONSTRAINT "predator_type_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sect_clans"
    ADD CONSTRAINT "sect_clans_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."sect"
    ADD CONSTRAINT "sect_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."clan"
    ADD CONSTRAINT "clan_content_source_id_fkey" FOREIGN KEY ("content_source_id") REFERENCES "public"."content_source"("id");

ALTER TABLE ONLY "public"."clan_disciplines"
    ADD CONSTRAINT "clan_disciplines_clan_id_fkey" FOREIGN KEY ("clan_id") REFERENCES "public"."clan"("id");

ALTER TABLE ONLY "public"."clan_disciplines"
    ADD CONSTRAINT "clan_disciplines_discipline_id_fkey" FOREIGN KEY ("discipline_id") REFERENCES "public"."discipline"("id");

ALTER TABLE ONLY "public"."discipline"
    ADD CONSTRAINT "discipline_prerequisite_id_fkey" FOREIGN KEY ("prerequisite_id") REFERENCES "public"."discipline"("id");

ALTER TABLE ONLY "public"."loresheet_benefit"
    ADD CONSTRAINT "loresheet_benefit_loresheet_id_fkey" FOREIGN KEY ("loresheet_id") REFERENCES "public"."loresheet"("id");

ALTER TABLE ONLY "public"."loresheet"
    ADD CONSTRAINT "loresheet_clan_id_fkey" FOREIGN KEY ("clan_id") REFERENCES "public"."clan"("id");

ALTER TABLE ONLY "public"."loresheet"
    ADD CONSTRAINT "loresheet_content_source_id_fkey" FOREIGN KEY ("content_source_id") REFERENCES "public"."content_source"("id");

ALTER TABLE ONLY "public"."loresheet"
    ADD CONSTRAINT "loresheet_sect_id_fkey" FOREIGN KEY ("sect_id") REFERENCES "public"."sect"("id");

ALTER TABLE ONLY "public"."power"
    ADD CONSTRAINT "power_content_source_id_fkey" FOREIGN KEY ("content_source_id") REFERENCES "public"."content_source"("id");

ALTER TABLE ONLY "public"."power"
    ADD CONSTRAINT "power_discipline_id_fkey" FOREIGN KEY ("discipline_id") REFERENCES "public"."discipline"("id");

ALTER TABLE ONLY "public"."power"
    ADD CONSTRAINT "power_prerequisite_id_fkey" FOREIGN KEY ("prerequisite_id") REFERENCES "public"."power"("id");

ALTER TABLE ONLY "public"."sect_clans"
    ADD CONSTRAINT "sect_clans_clan_id_fkey" FOREIGN KEY ("clan_id") REFERENCES "public"."clan"("id");

ALTER TABLE ONLY "public"."sect_clans"
    ADD CONSTRAINT "sect_clans_sect_id_fkey" FOREIGN KEY ("sect_id") REFERENCES "public"."sect"("id");

ALTER TABLE ONLY "public"."sect"
    ADD CONSTRAINT "sect_content_source_id_fkey" FOREIGN KEY ("content_source_id") REFERENCES "public"."content_source"("id");

CREATE POLICY "Enable read access for all users" ON "public"."clan" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."clan_disciplines" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."content_source" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."discipline" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."loresheet" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."loresheet_benefit" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."power" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."predator_type" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sect" FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."sect_clans" FOR SELECT USING (true);

ALTER TABLE "public"."clan" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."clan_disciplines" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."content_source" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."discipline" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."loresheet" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."loresheet_benefit" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."power" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."predator_type" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sect" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sect_clans" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."clan" TO "anon";
GRANT ALL ON TABLE "public"."clan" TO "authenticated";
GRANT ALL ON TABLE "public"."clan" TO "service_role";

GRANT ALL ON TABLE "public"."clan_disciplines" TO "anon";
GRANT ALL ON TABLE "public"."clan_disciplines" TO "authenticated";
GRANT ALL ON TABLE "public"."clan_disciplines" TO "service_role";

GRANT ALL ON SEQUENCE "public"."clan_disciplines_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clan_disciplines_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clan_disciplines_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."content_source" TO "anon";
GRANT ALL ON TABLE "public"."content_source" TO "authenticated";
GRANT ALL ON TABLE "public"."content_source" TO "service_role";

GRANT ALL ON TABLE "public"."discipline" TO "anon";
GRANT ALL ON TABLE "public"."discipline" TO "authenticated";
GRANT ALL ON TABLE "public"."discipline" TO "service_role";

GRANT ALL ON TABLE "public"."loresheet" TO "anon";
GRANT ALL ON TABLE "public"."loresheet" TO "authenticated";
GRANT ALL ON TABLE "public"."loresheet" TO "service_role";

GRANT ALL ON TABLE "public"."loresheet_benefit" TO "anon";
GRANT ALL ON TABLE "public"."loresheet_benefit" TO "authenticated";
GRANT ALL ON TABLE "public"."loresheet_benefit" TO "service_role";

GRANT ALL ON SEQUENCE "public"."loresheet_benefit_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."loresheet_benefit_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."loresheet_benefit_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."loresheet_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."loresheet_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."loresheet_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."power" TO "anon";
GRANT ALL ON TABLE "public"."power" TO "authenticated";
GRANT ALL ON TABLE "public"."power" TO "service_role";

GRANT ALL ON SEQUENCE "public"."power_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."power_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."power_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."predator_type" TO "anon";
GRANT ALL ON TABLE "public"."predator_type" TO "authenticated";
GRANT ALL ON TABLE "public"."predator_type" TO "service_role";

GRANT ALL ON SEQUENCE "public"."predator_type_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."predator_type_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."predator_type_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."sect" TO "anon";
GRANT ALL ON TABLE "public"."sect" TO "authenticated";
GRANT ALL ON TABLE "public"."sect" TO "service_role";

GRANT ALL ON TABLE "public"."sect_clans" TO "anon";
GRANT ALL ON TABLE "public"."sect_clans" TO "authenticated";
GRANT ALL ON TABLE "public"."sect_clans" TO "service_role";

GRANT ALL ON SEQUENCE "public"."sect_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sect_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sect_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
